:: FnEtcBootstrapSuites -o <ORG> -i <ORG_ID> [FLAGS...]
:: -- Caches the suites of one organization as
:: --   ORGANIZATIONS_<i>_SUITES_COUNT
:: --   ORGANIZATIONS_<i>_SUITE_<j>_COMMAND_IDENTIFIER / _FRIENDLY_IDENTIFIER
:: --   ORGANIZATIONS_<i>_SUITE_<j>_FRIENDLY_NAME / _ROOT_PATH / _ACTIVE
:: -- then recurses through FnEtcBootstrapProjects.
:: --
:: -- NOTE: No SETLOCAL -- this script exists to export ORGANIZATIONS_*.

@ECHO OFF

CALL FnEtcFlags %*
IF ERRORLEVEL 1 EXIT /B 1

SET "BS_ORG=%FLAG_ORG%"
SET "BS_ID=%FLAG_ID%"

IF NOT DEFINED BS_ORG GOTO :MISSING_ORG
IF NOT DEFINED BS_ID GOTO :MISSING_ID

CALL FnEtcCsvSuites "%BS_ORG%"
IF ERRORLEVEL 1 EXIT /B 1
CALL SET "GLOBAL_ORG_DIR_CACHE=%%GLOBAL_ORG_%BS_ORG%_DIR%%"

SET "BS_SUITES=%LPRE_SUITES%"
SET "BS_J=0"

FOR %%S IN (%BS_SUITES%) DO CALL :SUITE "%%S"

SET "ORGANIZATIONS_%BS_ID%_SUITES_COUNT=%BS_J%"
SET "BS_SUITES="
EXIT /B 0

:SUITE
    SET /A BS_J+=1
    CALL SET "BS_DIR=%%GLOBAL_SUITE_%~1_DIR%%"
    CALL SET "BS_NAME=%%GLOBAL_SUITE_%~1_NAME%%"
    CALL SET "BS_ROOT=%%GLOBAL_SUITE_%~1_ROOT%%"
    CALL SET "BS_ACTIVE=%%GLOBAL_SUITE_%~1_ACTIVE%%"
    SET "ORGANIZATIONS_%BS_ID%_SUITE_%BS_J%_COMMAND_IDENTIFIER=%~1"
    SET "ORGANIZATIONS_%BS_ID%_SUITE_%BS_J%_FRIENDLY_IDENTIFIER=%BS_DIR%"
    SET "ORGANIZATIONS_%BS_ID%_SUITE_%BS_J%_FRIENDLY_NAME=%BS_NAME%"
    SET "ORGANIZATIONS_%BS_ID%_SUITE_%BS_J%_ROOT_PATH=%BS_ROOT%"
    SET "ORGANIZATIONS_%BS_ID%_SUITE_%BS_J%_ACTIVE=%BS_ACTIVE%"
    IF NOT EXIST "%GLOBAL_DataPath%\Organizations\%GLOBAL_ORG_DIR_CACHE%\Suites\%BS_DIR%\Projects.csv" EXIT /B 0
    CALL FnEtcBootstrapProjects --org "%BS_ORG%" --org-id "%BS_ID%" --suite "%~1" --suite-id "%BS_J%"
    EXIT /B 0

:MISSING_ORG
    ECHO LeprechaunCLI:FnEtcBootstrapSuites[E]: Missing required flag -o ^<ORG^>
    EXIT /B 1

:MISSING_ID
    ECHO LeprechaunCLI:FnEtcBootstrapSuites[E]: Missing required flag -i ^<ORG_ID^>
    EXIT /B 1
