:: FnEtcBootstrapProjects --org <ORG> --org-id <ORG_ID> --suite <SUITE> --suite-id <SUITE_ID>
:: -- Caches the projects of one suite as
:: --   ORGANIZATIONS_<i>_SUITE_<j>_PROJECTS_COUNT
:: --   ORGANIZATIONS_<i>_SUITE_<j>_PROJECT_<k>_IDENTIFIER / _FRIENDLY_IDENTIFIER
:: --   ..._FRAMEWORK_IDENTIFIER / _FRIENDLY_NAME / _TYPE / _ROOT_PATH / _IS_EXTERNAL
:: --
:: -- NOTE: No SETLOCAL -- this script exists to export ORGANIZATIONS_*.

@ECHO OFF

CALL FnEtcFlags %*
IF ERRORLEVEL 1 EXIT /B 1

SET "BS_ORG=%FLAG_ORG%"
SET "BS_SUITE=%FLAG_SUITE%"
SET "BS_ORG_ID=%FLAG_ORG_ID%"
SET "BS_SUITE_ID=%FLAG_SUITE_ID%"

IF NOT DEFINED BS_ORG GOTO :MISSING_ORG
IF NOT DEFINED BS_SUITE GOTO :MISSING_SUITE

CALL FnEtcCsvProjects "%BS_ORG%" "%BS_SUITE%"
IF ERRORLEVEL 1 EXIT /B 1

SET "BS_PREFIX=ORGANIZATIONS_%BS_ORG_ID%_SUITE_%BS_SUITE_ID%"
SET "BS_PROJECTS=%GLOBAL_PROJECTS%"
SET "BS_K=0"

FOR %%P IN (%BS_PROJECTS%) DO CALL :PROJECT "%%P"

SET "%BS_PREFIX%_PROJECTS_COUNT=%BS_K%"
SET "BS_PROJECTS="
SET "BS_PREFIX="
EXIT /B 0

:PROJECT
    SET /A BS_K+=1
    CALL SET "BS_DIR=%%GLOBAL_PROJECT_%~1_DIR%%"
    CALL SET "BS_FRAMEWORK=%%GLOBAL_PROJECT_%~1_FRAMEWORK%%"
    CALL SET "BS_NAME=%%GLOBAL_PROJECT_%~1_NAME%%"
    CALL SET "BS_TYPE=%%GLOBAL_PROJECT_%~1_TYPE%%"
    CALL SET "BS_ROOT=%%GLOBAL_PROJECT_%~1_ROOT%%"
    CALL SET "BS_EXTERNAL=%%GLOBAL_PROJECT_%~1_EXTERNAL%%"
    SET "%BS_PREFIX%_PROJECT_%BS_K%_IDENTIFIER=%~1"
    SET "%BS_PREFIX%_PROJECT_%BS_K%_FRIENDLY_IDENTIFIER=%BS_DIR%"
    SET "%BS_PREFIX%_PROJECT_%BS_K%_FRAMEWORK_IDENTIFIER=%BS_FRAMEWORK%"
    SET "%BS_PREFIX%_PROJECT_%BS_K%_FRIENDLY_NAME=%BS_NAME%"
    SET "%BS_PREFIX%_PROJECT_%BS_K%_TYPE=%BS_TYPE%"
    SET "%BS_PREFIX%_PROJECT_%BS_K%_ROOT_PATH=%BS_ROOT%"
    SET "%BS_PREFIX%_PROJECT_%BS_K%_IS_EXTERNAL=%BS_EXTERNAL%"
    EXIT /B 0

:MISSING_ORG
    ECHO LeprechaunCLI:FnEtcBootstrapProjects[E]: Missing required flag --org ^<ORG^>
    EXIT /B 1

:MISSING_SUITE
    ECHO LeprechaunCLI:FnEtcBootstrapProjects[E]: Missing required flag --suite ^<SUITE^>
    EXIT /B 1
