:: FnEtcSelectOrganization -o <ORG>
:: -- Selects an organization from the bootstrap cache and exports
:: --   SELECTED_ORGANIZATION_COMMAND_IDENTIFIER / _FRIENDLY_IDENTIFIER
:: --   SELECTED_ORGANIZATION_FRIENDLY_NAME / _ROOT_PATH
:: -- Bootstraps first if the cache is cold.
:: --
:: -- NOTE: No SETLOCAL -- this script exists to export SELECTED_ORGANIZATION_*.

@ECHO OFF

CALL FnEtcFlags %*
IF ERRORLEVEL 1 EXIT /B 1

SET "SEARCH_ORG=%FLAG_ORG%"
IF NOT DEFINED SEARCH_ORG SET "SEARCH_ORG=%FLAG_ARG_1%"
IF NOT DEFINED SEARCH_ORG GOTO :MISSING_ORG

SET "SELECTED_ORGANIZATION_COMMAND_IDENTIFIER="
SET "SELECTED_ORGANIZATION_FRIENDLY_IDENTIFIER="
SET "SELECTED_ORGANIZATION_FRIENDLY_NAME="
SET "SELECTED_ORGANIZATION_ROOT_PATH="

IF NOT DEFINED ORGANIZATIONS_COUNT CALL FnEtcBootstrapOrganizations
IF ERRORLEVEL 1 EXIT /B 1

FOR /L %%I IN (1,1,%ORGANIZATIONS_COUNT%) DO CALL :TRY %%I

IF NOT DEFINED SELECTED_ORGANIZATION_COMMAND_IDENTIFIER GOTO :NOT_FOUND
IF DEFINED FLAG_VERBOSE ECHO LeprechaunCLI:FnEtcSelectOrganization[D]: Organization selected: %SELECTED_ORGANIZATION_COMMAND_IDENTIFIER%
EXIT /B 0

:TRY
    IF DEFINED SELECTED_ORGANIZATION_COMMAND_IDENTIFIER EXIT /B 0
    CALL SET "SELECT_ROW=%%ORGANIZATIONS_%~1_COMMAND_IDENTIFIER%%"
    IF /I NOT "%SELECT_ROW%"=="%SEARCH_ORG%" EXIT /B 0
    SET "SELECTED_ORGANIZATION_COMMAND_IDENTIFIER=%SELECT_ROW%"
    CALL SET "SELECTED_ORGANIZATION_FRIENDLY_IDENTIFIER=%%ORGANIZATIONS_%~1_FRIENDLY_IDENTIFIER%%"
    CALL SET "SELECTED_ORGANIZATION_FRIENDLY_NAME=%%ORGANIZATIONS_%~1_FRIENDLY_NAME%%"
    CALL SET "SELECTED_ORGANIZATION_ROOT_PATH=%%ORGANIZATIONS_%~1_ROOT_PATH%%"
    SET "SELECT_ROW="
    EXIT /B 0

:NOT_FOUND
    ECHO LeprechaunCLI:FnEtcSelectOrganization[E]: Unknown organization "%SEARCH_ORG%"
    EXIT /B 1

:MISSING_ORG
    ECHO LeprechaunCLI:FnEtcSelectOrganization[E]: Missing required flag -o ^<ORG^>
    EXIT /B 1
